name: bootpay
description: A Bootpay plugin that provides payment api on Android, iOS and Web.

version: 5.0.22

homepage: https://www.bootpay.co.kr
repository: https://github.com/bootpay/bootpay_flutter.git
environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # [배포용] pub.dev 버전 - 배포 시 아래 주석 해제
  bootpay_webview_flutter: ^4.12.3
  bootpay_webview_flutter_android: ^4.10.57
  bootpay_webview_flutter_wkwebview: ^3.23.27

  # [로컬 테스트용] 로컬 경로 - 테스트 완료 후 위 배포용으로 변경
#  bootpay_webview_flutter:
#    path: ../bootpay_flutter_webview/bootpay_webview_flutter
#  bootpay_webview_flutter_android:
#    path: ../bootpay_flutter_webview/bootpay_webview_flutter_android
#  bootpay_webview_flutter_wkwebview:
#    path: ../bootpay_flutter_webview/bootpay_webview_flutter_wkwebview

#  bootpay_webview_flutter: 4.3.2
#  bootpay_webview_flutter_android: 3.17.1
#  bootpay_webview_flutter_wkwebview: 3.4.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.5
  fluttertoast: ^8.2.8
  http: ^1.3.0
  package_info_plus: ^8.2.1
  encrypt: ^5.0.3
  get: ^4.6.6
  intl: ">=0.19.0 <1.0.0"
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  plugin:
    platforms:
      android:
        default_package: bootpay_webview_flutter_android
      ios:
        default_package: bootpay_webview_flutter_wkwebview
      web:

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
#  plugin:
#    platforms:
#      android:
#        package: com.example.bootpay_flutter
#        pluginClass: BootpayFlutterPlugin
#      ios:
#        pluginClass: BootpayFlutterPlugin


#      web:
#        pluginClass: BootpayWeb
#        fileName: web/bootpay_web.dart


  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
